### ISSUE TITLE
disable swap is not persistent

### ISSUE THREAD

**Issue by flo-weber** [world-direct/k8s-setup#73]
After kernel update and reboot of the hosts swap is on every reboot enabled again

kubelet.service don't start until swap is disabled

**Comment by gprossliner** [comment]
/etc/fstab needs to match the regex `(\/swapfile)`
https://github.com/world-direct/k8s-setup/blob/master/lib/ansible/roles/lnx-setup/handlers/main.yml#L7

cat /etc/fstab auf centos7:
```
/dev/mapper/centos_k8sdev--ctrl1-root /                       xfs     defaults        0 0
UUID=0abb1bec-8733-40e3-ab33-62f434581f94 /boot                   xfs     defaults        0 0
UUID=94F3-548A          /boot/efi               vfat    umask=0077,shortname=winnt 0 0
/dev/mapper/centos_k8sdev--ctrl1-swap swap                    swap    defaults        0 0
```

Die regex matched nicht. Da "swap" und nicht "swapfile".

**Comment by gprossliner** [comment]
cat /etc/fstab in Vargrant centos/7 Box:
```
UUID=8ac075e3-1124-4bb6-bef7-a6811bf8b870 /                       xfs     defaults        0 0
/swapfile none swap defaults 0 0
```

**Comment by gprossliner** [comment]
new regex: https://regex101.com/r/F4s7l1/3
