### ISSUE TITLE
Pods are unable to resolve full qualified Ingress adresses

### ISSUE THREAD

**Issue by flo-weber** [world-direct/k8s-setup#85]
CoreDNS has the following configuration by default (`kubectl get configmap coredns -n kube-system -oyam`)

```yaml
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready

        # This causes the 'k8stest.local' domain to be resolved by CoreDNS
        # To use the external DNS, it should be:
        # --> kubernetes in-addr.arpa ip6.arpa 
        kubernetes k8stest.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
```

The cluster dns address should be transparent. When a pod uses a internal kubernetes service, it should always use the one of these:

``` sh
# executed in a pod
curl dashboard-metrics-scraper    # service in same namespace (kube-dashboard)
nslookup kubernetes-dashboard kube-dns.kube-system # nslookup explicilty to kube-dns
curl https://kubernetes   # the kubernetes API server (see kubectl get service)
```

DNS knows nothing about Ingress Hosts, so to contact the dashboard service with a cluster-qualified name, you have to use `kubernetes-dashboard.kube-dashboard.svc.k8stest.local`, although the Ingress Host is 'dashboard.k8stest.local'.

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

We should check if anything 'bad' happens, when we remove the cluster-dns-name from kube-dns, so that pods can also consume services by their ingress hosts.

**Comment by gprossliner** [comment]
the 'kubernetes' CoreDNS plugin: https://github.com/coredns/coredns/blob/master/plugin/kubernetes/README.md

'fallthrough' may work, when pointing to the external DNS. @flo-weber

**Comment by flo-weber** [comment]
On the pods were the cluster resources must be accessible external in the cluster we must set the DnsPolicy: to Default from ClusterFirst than the dns resolution is as expected
